Repository clue/socket-raw, pull requests merged in 2020-11, with the labels that each got.

#57 Run tests on PHPUnit 9 and update PHPUnit configuration schema for PHPUnit 9.3
  .gitattributes
  .travis.yml
  composer.json
  phpunit.xml.dist
  phpunit.xml.legacy
  tests/FactoryTest.php
  tests/SocketTest.php
Labels: maintenance

#60 Drop legacy HHVM support
  .travis.yml
  README.md
  tests/SocketTest.php
Labels: maintenance

#58 Use GitHub actions for continuous integration (CI)
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: maintenance

#61 Support PHP 8, use Socket object instead of socket resource
  .github/workflows/ci.yml
  README.md
  src/Exception.php
  src/Factory.php
  src/Socket.php
  tests/FactoryTest.php
  tests/SocketTest.php
Labels: new feature

#63 Minor strict type improvements (phpstan)
  src/Socket.php
Labels: easy pick, maintenance

#62 Prepare v1.5.0
  CHANGELOG.md
  README.md
  composer.json
Labels: maintenance
